houses: houses.o print_header.o print_one_house.o print_houses.o print_price.o
	gcc -o houses houses.o print_header.o print_one_house.o print_houses.o print_price.o 

run:
	./houses
	
clean:
	rm *.o

