houses: houses.o print_header.o print_one_house.o print_houses.o print_price.o print_bedrooms.o print_lot.o
	gcc -o houses houses.o print_header.o print_one_house.o print_houses.o print_price.o print_bedrooms.o print_lot.o

run:
	./houses
	
clean:
	rm *.o

